---

- name: Install haproxy and keepalived
  apt: name={{ item }} state=latest
  tags:
    - haproxy
    - keepalived
  with_items:
    - haproxy
    - keepalived

- name: Gather facts from ALL hosts (regardless of limit or tags)
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  with_items: "{{ groups['patroni'] }}"
  tags:
    - haproxy
    - keepalived

- name: Put haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=yes
  tags: haproxy

- name: Put keepalived configuration
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=yes
  tags: keepalived

- name: Create vitrual interface
  command: ifconfig {{ ansible_default_ipv4.interface }}:vip {{ virtual_ipaddress }}
  tags: keepalived

- name: Restart and enable haproxy
  service: name=haproxy state=restarted enabled=yes
  tags: haproxy

- name: Restart and enable keepalived
  service: name=keepalived state=restarted enabled=yes
  tags: keepalived
